import { Role, Faction, RoleType, Difficulty, NightAbilityKind, DayAbilityKind, ResultTiming } from '@deceit/shared';

export const ALL_ROLES: Role[] = [
  // --- فريق المملكة (KINGDOM) ---
  {
    id: 'king',
    name: 'الملك',
    nameEn: 'King',
    icon: '👑',
    cardImage: '/cards/deset_king.png',
    faction: Faction.kingdom,
    roleType: RoleType.special,
    difficulty: Difficulty.easy,
    description: 'حاكم المملكة. يجب حمايتك بأي ثمن.',
    descriptionEn: 'Ruler of the realm. Must be protected at all costs.',
    lore: 'الوريث الشرعي للعرش، يحمل آمال مملكته على عاتقه.',
    loreEn: 'The rightful heir to the throne, carrying the hopes of the kingdom on his shoulders.',
    goal: 'حماية منصب العرش والقضاء على جميع أعضاء الظلال.',
    goalEn: 'Protect the Throne position and eliminate all Shadow members.',
    tips: ['ابقَ متخفياً خلف حراسك.', 'استمع جيداً لنصائح الوزير.'],
    tipsEn: ['Stay hidden behind your guards.', "Listen closely to the Minister's advice."],
    warnings: ['خلو العرش من حكام المملكة يمنح النصر للظلال.'],
    warningsEn: ['A vacant Throne grants immediate victory to the Shadows.'],
    priority: 100,
    nightAbilityKind: NightAbilityKind.none,
    isMandatory: true,
    constraints: [
      'لا تستطيع استخدام أي قدرة ليلية.',
      'إذا مِتَّ ينتقل العرش إلى ولي العهد إن كان حياً ليصون منصب العرش.',
      'إن لم يكن ولي العهد حياً يخلو العرش وتخسر المملكة.',
    ],
    constraintsEn: [
      'You cannot perform any night actions.',
      'If you die, the Throne transfers to the Crown Prince if alive.',
      'If no heir lives, the Throne falls and the Kingdom loses.',
    ],
  },
  {
    id: 'crown_prince',
    name: 'ولي العهد',
    nameEn: 'Crown Prince',
    icon: '🎖️',
    cardImage: '/cards/deset_crown_prince.png',
    faction: Faction.kingdom,
    roleType: RoleType.special,
    difficulty: Difficulty.medium,
    description: 'إذا مات الملك، ستتولى العرش مكانه تلقائيًا لحماية منصب العرش.',
    descriptionEn: 'If the King dies, you automatically take the throne to protect the Throne position.',
    lore: 'الوريث الشرعي للعرش، يستعد لليوم الذي سيقود فيه المملكة.',
    loreEn: 'The rightful heir, preparing for the day he will lead the kingdom.',
    goal: 'حماية منصب العرش والقضاء على جميع أعضاء فريق الظلال.',
    goalEn: 'Protect the Throne position and eliminate all members of the Shadow faction.',
    tips: ['أنت القائد البديل.', 'لا تكشف عن هويتك مبكراً.'],
    tipsEn: ['You are the fallback leader.', 'Do not reveal your identity early.'],
    passiveAbility: 'عند موت الملك، يصبح ولي العهد هو الملك الجديد تلقائيًا دون تصويت.',
    passiveAbilityEn: "Upon the King's death, the Crown Prince automatically becomes the new King without a vote.",
    priority: 90,
    nightAbilityKind: NightAbilityKind.none,
    constraints: [
      'التحول إلى الملك يحدث تلقائياً فور موت الملك.',
      'لا يحتاج إلى تصويت أو موافقة من أحد.',
      'لا يتحول إذا كان قد مات قبل الملك.',
    ],
    constraintsEn: [
      "Transition to King occurs automatically upon the King's death.",
      'Requires no vote or approval from anyone.',
      'Does not transition if already dead before the King.',
    ],
  },
  {
    id: 'minister',
    name: 'الوزير',
    nameEn: 'Minister',
    icon: '📜',
    cardImage: '/cards/deset_vizier.png',
    faction: Faction.kingdom,
    roleType: RoleType.support,
    difficulty: Difficulty.medium,
    description: 'يصله تقرير صحيح عن فريق أحد اللاعبين الأحياء.',
    descriptionEn: "Receives an accurate report about a living player's faction.",
    lore: 'كاتم أسرار الملك ومستشاره الأكثر ثقة.',
    loreEn: "Keeper of royal secrets and the King's most trusted advisor.",
    goal: 'كشف أعضاء الظلال وإرشاد فريق المملكة.',
    goalEn: 'Expose Shadow members and guide the Kingdom team.',
    abilityDescription: 'يصلك اسم لاعب حي والفريق الذي ينتمي إليه. النظام هو من يختار.',
    abilityDescriptionEn: 'You receive the name of a living player and their faction.',
    priority: 80,
    nightAbilityKind: NightAbilityKind.none,
    resultTiming: ResultTiming.instant,
    cooldown: 1,
    cooldownScale: [{ maxPlayers: 11, cooldownDays: 2 }, { maxPlayers: 16, cooldownDays: 3 }],
    constraints: ['يصلك تقرير جديد كل يوم ما دمت حياً.', 'المعلومة صحيحة دائماً ولا تؤثر عليها قدرة المزور.'],
    constraintsEn: ['Receive a new report each day while alive.', "Forger's ability does not affect your report."],
  },
  {
    id: 'guard',
    name: 'الحارس',
    nameEn: 'Guard',
    icon: '🛡️',
    cardImage: '/cards/deset_guard.png',
    faction: Faction.kingdom,
    roleType: RoleType.support,
    difficulty: Difficulty.easy,
    description: 'يحمي أفراد المملكة من محاولات الاغتيال.',
    descriptionEn: 'Protects Kingdom members from assassination attempts.',
    lore: 'مدافع صلب مستعد للتضحية بحياته من أجل الآخرين.',
    loreEn: 'A steadfast defender ready to sacrifice his life for others.',
    goal: 'حماية الأعضاء المهمين في فريق المملكة.',
    goalEn: 'Protect key Kingdom members.',
    abilityDescription: 'إذا تعرض اللاعب لأول هجوم قاتل مباشر خلال تلك الليلة، يتم إلغاء الهجوم.',
    abilityDescriptionEn: 'If the target suffers the first direct lethal attack tonight, the attack is cancelled.',
    priority: 70,
    nightAbilityKind: NightAbilityKind.protect,
    targetCount: 1,
    canTargetSelf: true,
    resultTiming: ResultTiming.none,
    constraints: ['يختار لاعبًا واحدًا كل ليلة لحمايته.', 'الحماية تمنع أول هجوم قاتل مباشر فقط.', 'لا تمنع السم.'],
    constraintsEn: ['Choose one player each night to protect.', 'Shields against the first direct lethal attack only.', 'Does not prevent poison.'],
  },
  {
    id: 'doctor',
    name: 'الطبيب',
    nameEn: 'Doctor',
    icon: '🧪',
    cardImage: '/cards/deset_physician.png',
    faction: Faction.kingdom,
    roleType: RoleType.support,
    difficulty: Difficulty.medium,
    description: 'يعالج اللاعبين من الهجمات القابلة للشفاء والسموم.',
    descriptionEn: 'Treats players from curable attacks and poison.',
    lore: 'خبير في الطب والأعشاب في زمن الأوبئة والظلال.',
    loreEn: 'An expert in medicine and herbs in times of plagues and shadows.',
    goal: 'إبقاء أعضاء فريق المملكة على قيد الحياة.',
    goalEn: 'Keep Kingdom team members alive.',
    abilityDescription: 'علاج لاعب من الآثار السلبية والسموم.',
    abilityDescriptionEn: 'Treat a player from negative effects and poison.',
    priority: 60,
    nightAbilityKind: NightAbilityKind.heal,
    targetCount: 1,
    canTargetSelf: true,
    resultTiming: ResultTiming.none,
    constraints: ['تختار لاعباً واحداً كل ليلة.', 'لا تستطيع علاج نفسك ليلتين متتاليتين.', 'علاج السم ينقذ المسموم.'],
    constraintsEn: ['Choose one player each night.', 'Cannot treat self two nights in a row.', 'Poison cure saves the poisoned target.'],
  },
  {
    id: 'investigator',
    name: 'المحقق',
    nameEn: 'Seer',
    icon: '🔍',
    cardImage: '/cards/deset_investigator.png',
    faction: Faction.kingdom,
    roleType: RoleType.support,
    difficulty: Difficulty.medium,
    description: 'يجمع المعلومات لكشف أفراد فريق الظلال.',
    descriptionEn: 'Gathers clues to unmask members of the Shadow faction.',
    lore: 'لا يخفى على عينيه أي سر، يبحث دائماً عن الحقيقة.',
    loreEn: 'No secret escapes his eyes, constantly searching for truth.',
    goal: 'كشف أعضاء فريق الظلال.',
    goalEn: 'Expose members of the Shadow faction.',
    abilityDescription: 'يحصل على معلومة صحيحة عن الفريق، إلا إذا كان الهدف متأثراً بقدرة المزور.',
    abilityDescriptionEn: 'Receives accurate info about a player, unless affected by the Forger.',
    priority: 50,
    nightAbilityKind: NightAbilityKind.investigate,
    targetCount: 1,
    resultTiming: ResultTiming.nextTurn,
    cooldown: 1,
    cooldownScale: [{ maxPlayers: 11, cooldownDays: 2 }, { maxPlayers: 16, cooldownDays: 3 }],
    constraints: ['يختار لاعبًا واحدًا كل ليلة للتحقيق معه.', 'إذا كان الهدف متأثراً بالتزوير تظهر نتيجة خاطئة.', 'لا يراقب نفسه.'],
    constraintsEn: ['Choose one player each night to investigate.', 'If target is forged, receives false info.', 'Cannot target self.'],
  },
  {
    id: 'judge',
    name: 'القاضي',
    nameEn: 'Judge',
    icon: '⚖️',
    cardImage: '/cards/deset_judge.png',
    faction: Faction.kingdom,
    roleType: RoleType.special,
    difficulty: Difficulty.hard,
    description: 'يمتلك سلطة قانونية تمكنه من التدخل في التصويت.',
    descriptionEn: 'Holds legal authority enabling intervention in voting results.',
    lore: 'السلطة العليا للقانون والعدالة.',
    loreEn: 'Supreme authority of law and justice.',
    goal: 'منع استبعاد الأبرياء من فريق المملكة.',
    goalEn: 'Prevent execution of innocent Kingdom members.',
    abilityDescription: 'يستطيع القاضي الاعتراض على نتيجة التصويت.',
    abilityDescriptionEn: 'The Judge may veto a voting result.',
    priority: 40,
    nightAbilityKind: NightAbilityKind.none,
    dayAbilityKind: DayAbilityKind.veto,
    cooldown: 3,
    maxUses: 7,
    constraints: ['عند تفعيل الاعتراض يُلغى التصويت ولا يموت أحد.', 'بعد الاعتراض تنتظر 3 أيام قبل تكراره.'],
    constraintsEn: ['When vetoed, vote is cancelled and no player dies.', 'Requires 3-day cooldown between uses.'],
  },
  {
    id: 'wizard',
    name: 'الساحر',
    nameEn: 'Wizard',
    icon: '🧙',
    cardImage: '/cards/deset_wizard.png',
    faction: Faction.kingdom,
    roleType: RoleType.special,
    difficulty: Difficulty.medium,
    description: 'يمنع لاعباً واحداً من الكلام في اليوم التالي.',
    descriptionEn: 'Prevents one player from speaking during the next day.',
    lore: 'ممارس للسحر القديم والمحرم.',
    loreEn: 'Practitioner of ancient and forbidden magic.',
    goal: 'السيطرة على النقاش وكشف الكاذبين.',
    goalEn: 'Control discussion and expose liars.',
    abilityDescription: 'إسكات لاعب ومنعه من الحديث في اليوم التالي.',
    abilityDescriptionEn: 'Silence a player and prevent them from speaking the next day.',
    priority: 30,
    nightAbilityKind: NightAbilityKind.silence,
    targetCount: 1,
    noRepeatTarget: true,
    constraints: ['الهدف لا يستطيع الكلام في النقاش.', 'لا تستطيع اختيار نفس اللاعب ليلتين متتاليتين.'],
    constraintsEn: ['Target cannot speak during next day discussion.', 'Cannot choose same player consecutive nights.'],
  },
  {
    id: 'priest',
    name: 'الكاهن',
    nameEn: 'Priest',
    icon: '📿',
    cardImage: '/cards/deset_priest.png',
    faction: Faction.kingdom,
    roleType: RoleType.support,
    difficulty: Difficulty.medium,
    description: 'يزيل اللعنات والآثار السلبية عن اللاعبين.',
    descriptionEn: 'Cleanses curses and negative effects from players.',
    lore: 'منارة الضوء في الظلام الزاحف.',
    loreEn: 'A beacon of light in the creeping dark.',
    goal: 'تطهير المملكة من الشرور.',
    goalEn: 'Purify the realm of evil.',
    abilityDescription: 'تطهير لاعب من التزوير واللعنات وجميع الآثار السلبية.',
    abilityDescriptionEn: 'Cleanse a player of forgery, curses, and negative effects.',
    priority: 20,
    nightAbilityKind: NightAbilityKind.heal,
    targetCount: 1,
    canTargetSelf: true,
    resultTiming: ResultTiming.none,
    constraints: ['تزيل تأثيراً سلبياً واحداً قابلاً للإزالة.', 'تستطيع استهداف نفسك.'],
    constraintsEn: ['Removes active negative effect per use.', 'Can target self.'],
  },
  {
    id: 'messenger',
    name: 'الرسول',
    nameEn: 'Messenger',
    icon: '🕊️',
    cardImage: '/cards/deset_messenger.png',
    faction: Faction.kingdom,
    roleType: RoleType.support,
    difficulty: Difficulty.hard,
    description: 'ينقل المعلومات السرية بين أفراد المملكة.',
    descriptionEn: 'Conveys secret information between members of the realm.',
    lore: 'أسرع من الريح، ينقل الأخبار عبر الحدود.',
    loreEn: 'Faster than the wind, carrying news across borders.',
    goal: 'كشف الروابط بين اللاعبين.',
    goalEn: 'Uncover connections between players.',
    abilityDescription: 'يعرف أن لاعبين ينتميان إلى نفس الفريق أم لا.',
    abilityDescriptionEn: 'Learns whether two players belong to the same faction.',
    priority: 15,
    nightAbilityKind: NightAbilityKind.compare,
    targetCount: 2,
    resultTiming: ResultTiming.nextTurn,
    cooldown: 1,
    spendsCooldownWhenBlocked: true,
    constraints: ['يختار لاعبين اثنين.', 'يعرف إن كانا من نفس الفريق أم لا دون تحديد اسم الفريق.'],
    constraintsEn: ['Choose two players.', 'Learns if they share a faction without learning faction name.'],
  },
  {
    id: 'knight',
    name: 'الفارس',
    nameEn: 'Knight',
    icon: '⚔️',
    cardImage: '/cards/deset_knight.png',
    faction: Faction.kingdom,
    roleType: RoleType.attack,
    difficulty: Difficulty.hard,
    description: 'يمكنه التضحية بنفسه لإنقاذ لاعب آخر.',
    descriptionEn: 'Can sacrifice himself to save another player.',
    lore: 'الشهامة لا تموت طالما قلبه ينبض.',
    loreEn: 'Chivalry never dies while his heart beats.',
    goal: 'حماية الملك بأي ثمن.',
    goalEn: 'Protect the King at any cost.',
    abilityDescription: 'إذا تعرض هدفك لهجوم قاتل هذه الليلة تموت بدلاً منه.',
    abilityDescriptionEn: 'Become a shield for a player; if targeted by lethal attack, die in their place.',
    priority: 10,
    nightAbilityKind: NightAbilityKind.sacrifice,
    targetCount: 1,
    constraints: ['عند التضحية تموت أنت بدلاً من هدفك.', 'تستطيع استخدام قدرتك كل ليلة.'],
    constraintsEn: ['Upon sacrifice, die instead of target.', 'Can use every night while alive.'],
  },
  {
    id: 'royal_guard',
    name: 'الحارس الملكي',
    nameEn: 'Royal Guard',
    icon: '💂',
    cardImage: '/cards/deset_royal_guard.png',
    faction: Faction.kingdom,
    roleType: RoleType.support,
    difficulty: Difficulty.easy,
    description: 'يحمي الملك تلقائياً إذا تعرض لهجوم.',
    descriptionEn: 'Automatically protects the King if attacked.',
    lore: 'لا يتحركون إلا إذا تحرك الملك.',
    loreEn: 'They move only when the King is threatened.',
    goal: 'إبقاء الملك حياً.',
    goalEn: 'Keep the King alive.',
    passiveAbility: 'لا يمكن مهاجمة الملك طالما الحارس الملكي حياً.',
    passiveAbilityEn: 'The King cannot be attacked while the Royal Guard is alive.',
    priority: 4,
    nightAbilityKind: NightAbilityKind.none,
    constraints: ['القدرة تلقائية ولا تحتاج لاختيار هدف.', 'تعمل فقط عندما يكون الملك هو هدف الهجوم.'],
    constraintsEn: ['Automatic ability.', 'Functions only when King is attack target.'],
  },
  {
    id: 'hermit',
    name: 'الناسك',
    nameEn: 'Hermit',
    icon: '🛖',
    cardImage: '/cards/deset_hermit.png',
    faction: Faction.kingdom,
    roleType: RoleType.special,
    difficulty: Difficulty.medium,
    description: 'لا يمكن استهدافه في أول ليلتين من المباراة.',
    descriptionEn: 'Cannot be targeted during the first two nights of the match.',
    lore: 'العيش في عزلة له فوائده.',
    loreEn: 'Living in isolation has its rewards.',
    goal: 'البقاء على قيد الحياة ومساعدة المملكة.',
    goalEn: 'Survive and assist the Kingdom.',
    passiveAbility: 'منيع ضد جميع الأعمال الليلية في الليلة 1 و 2.',
    passiveAbilityEn: 'Immune to all night actions during Night 1 and Night 2.',
    immuneThroughNight: 2,
    priority: 3,
    nightAbilityKind: NightAbilityKind.none,
    constraints: ['الحماية تبدأ من الليلة الأولى وحتى نهاية الليلة الثانية.'],
    constraintsEn: ['Immunity applies for Night 1 and Night 2.'],
  },
  {
    id: 'citizen',
    name: 'المواطن',
    nameEn: 'Citizen',
    icon: '👨‍🌾',
    cardImage: '/cards/deset_citizen.png',
    faction: Faction.kingdom,
    roleType: RoleType.neutral,
    difficulty: Difficulty.easy,
    description: 'مواطن عادي في المملكة.',
    descriptionEn: 'An ordinary citizen of the realm.',
    lore: 'العمود الفقري للمملكة، وأكثرهم عرضة للخطر.',
    loreEn: 'Backbone of the kingdom, most vulnerable to danger.',
    goal: 'النقاش والتصويت لإخراج أعضاء الظلال.',
    goalEn: 'Discuss and vote to eliminate Shadow members.',
    priority: 0,
    nightAbilityKind: NightAbilityKind.none,
    constraints: ['لا تملك أي قدرة ليلية.'],
    constraintsEn: ['No night abilities.'],
  },

  // --- فريق الظلال (SHADOWS) ---
  {
    id: 'shadow_leader',
    name: 'زعيم الظلال',
    nameEn: 'Shadow Leader',
    icon: '🌑',
    cardImage: '/cards/deset_shadow_leader.png',
    faction: Faction.shadow,
    roleType: RoleType.special,
    difficulty: Difficulty.hard,
    description: 'يحدد الهدف المقترح لهجوم الظلال كل ليلة.',
    descriptionEn: "Proposes the targeted victim for the Shadow attack each night.",
    lore: 'العقل المدبر وراء المؤامرة للإطاحة بالملك.',
    loreEn: 'Mastermind behind the conspiracy to overthrow the King.',
    goal: 'أن يصبح عدد أعضاء الظلال مساوياً أو أكثر من فريق المملكة.',
    goalEn: 'Equal or exceed Kingdom member count.',
    abilityDescription: 'اختر هدفًا مقترحًا لهجوم القاتل. القاتل يرى الاقتراح ويقرر اتباعه أو عصيانه.',
    abilityDescriptionEn: 'Choose a proposed target for Assassin. Assassin sees proposal and decides.',
    priority: 110,
    isMandatory: false,
    nightAbilityKind: NightAbilityKind.mark,
    targetCount: 1,
    canTargetAllies: false,
    constraints: ['اقتراحك ليس أمراً مُلزماً للقاتل.', 'ترى وحدك اللاعبين المحصّنين.'],
    constraintsEn: ['Proposal is not binding on Assassin.', 'Only you see immune players.'],
  },
  {
    id: 'assassin',
    name: 'القاتل',
    nameEn: 'Assassin',
    icon: '🔪',
    cardImage: '/cards/deset_assassin.png',
    faction: Faction.shadow,
    roleType: RoleType.attack,
    difficulty: Difficulty.medium,
    description: 'ينفذ الاغتيال بناءً على اقتراح الزعيم أو اختياره الخاص.',
    descriptionEn: "Executes assassination based on Leader's proposal or own choice.",
    lore: 'محترف لا يجد متعة في عمله، لكنه يتقنه.',
    loreEn: 'A professional taking no joy in work, but mastering it.',
    goal: 'القضاء على أعضاء فريق المملكة.',
    goalEn: 'Eliminate Kingdom members.',
    abilityDescription: 'اختر هدفًا للاغتيال. يمكنك اتباع اقتراح الزعيم أو اختيار هدف مختلف.',
    abilityDescriptionEn: 'Choose assassination target. Follow Leader proposal or select different target.',
    priority: 105,
    isMandatory: true,
    nightAbilityKind: NightAbilityKind.attack,
    targetCount: 1,
    canTargetAllies: false,
    constraints: ['القرار النهائي في الهجوم لك.', 'لا تستطيع اختيار أحد من الظلال.'],
    constraintsEn: ['Final attack decision is yours.', 'Cannot target Shadow allies.'],
  },
  {
    id: 'spy',
    name: 'الجاسوس',
    nameEn: 'Spy',
    icon: '🕶️',
    cardImage: '/cards/deset_spy.png',
    faction: Faction.shadow,
    roleType: RoleType.support,
    difficulty: Difficulty.medium,
    description: 'يتتبع تحركات اللاعبين ويجمع المعلومات عن زوار هدفه.',
    descriptionEn: 'Tracks player movements and gathers info on visitors targeting your ward.',
    lore: 'يراقب دائماً من زوايا الغرفة المظلمة.',
    loreEn: 'Watches from dark corners of the room.',
    goal: 'جمع المعلومات لصالح فريق الظلال.',
    goalEn: 'Gather intel for Shadow team.',
    abilityDescription: 'يعرف الأشخاص الذين تواصلوا مع الهدف بقدرة ليلية.',
    abilityDescriptionEn: 'Learn who targeted target with night ability without knowing roles.',
    priority: 60,
    nightAbilityKind: NightAbilityKind.watch,
    targetCount: 1,
    canTargetAllies: false,
    resultTiming: ResultTiming.nextTurn,
    constraints: ['تعرف من استهدف ذلك اللاعب.', 'لا تعرف وظيفة أو دور أي شخص ظهر في النتيجة.'],
    constraintsEn: ['Learn who targeted player.', 'Do not learn roles of visitors.'],
  },
  {
    id: 'poisoner',
    name: 'السمّام',
    nameEn: 'Poisoner',
    icon: '🧪',
    cardImage: '/cards/deset_poisoner.png',
    faction: Faction.shadow,
    roleType: RoleType.attack,
    difficulty: Difficulty.hard,
    description: 'يسمم لاعباً ليموت في الليلة التالية.',
    descriptionEn: 'Poisons a player to die the following night.',
    lore: 'الموت البطيء غالباً ما يكون الأكثر تأكيداً.',
    loreEn: 'Slow death is often the most certain.',
    goal: 'القضاء على أعضاء فريق المملكة تدريجياً.',
    goalEn: 'Eliminate Kingdom members gradually.',
    abilityDescription: 'تسميم لاعب؛ سيموت بعد ليلة واحدة إذا لم يعالج.',
    abilityDescriptionEn: 'Poison a player; dies after one night unless cured.',
    priority: 55,
    nightAbilityKind: NightAbilityKind.poison,
    targetCount: 1,
    canTargetAllies: false,
    constraints: ['يموت الهدف في الليلة التالية إن بقي السم فعّالاً.', 'الحارس لا يصد السم.'],
    constraintsEn: ['Target dies next night if poison remains.', 'Guard does not block poison.'],
  },
  {
    id: 'saboteur',
    name: 'المخرب',
    nameEn: 'Saboteur',
    icon: '🧨',
    cardImage: '/cards/deset_saboteur.png',
    faction: Faction.shadow,
    roleType: RoleType.support,
    difficulty: Difficulty.medium,
    description: 'يعطل خطط المملكة بإفساد قدرات خصومه.',
    descriptionEn: 'Disrupts Kingdom plans by spoiling opponent abilities.',
    lore: 'أفضل الخطط يسهل إفسادها.',
    loreEn: 'The best plans are easily ruined.',
    goal: 'تعطيل المتخصصين في فريق المملكة.',
    goalEn: 'Disable Kingdom specialists.',
    abilityDescription: 'يمنع لاعبًا من استخدام قدرته خلال الليلة الحالية.',
    abilityDescriptionEn: 'Prevent a player from using active ability during current night.',
    priority: 50,
    nightAbilityKind: NightAbilityKind.block,
    targetCount: 1,
    noRepeatTarget: true,
    canTargetAllies: false,
    constraints: ['القدرة النشطة للهدف لا تعمل خلال تلك الليلة.', 'لا تستطيع استهداف نفس اللاعب ليلتين متتاليتين.'],
    constraintsEn: ['Active ability of target disabled tonight.', 'Cannot target same player consecutive nights.'],
  },
  {
    id: 'forger',
    name: 'المزور',
    nameEn: 'Forger',
    icon: '🖋️',
    cardImage: '/cards/deset_forger.png',
    faction: Faction.shadow,
    roleType: RoleType.support,
    difficulty: Difficulty.hard,
    description: 'متخصص في تضليل المحققين وإخفاء الحقيقة.',
    descriptionEn: 'Specialist in misleading investigators and concealing truth.',
    lore: 'الحقيقة هي ما أكتبه بيدي فقط.',
    loreEn: 'Truth is only what I write with my hand.',
    goal: 'تضليل محققي فريق المملكة.',
    goalEn: 'Mislead Kingdom investigators.',
    abilityDescription: 'يجعل نتيجة تحقيق واحدة تظهر بمعلومة خاطئة.',
    abilityDescriptionEn: 'Causes one investigation result to return false information.',
    priority: 40,
    nightAbilityKind: NightAbilityKind.frame,
    targetCount: 1,
    noRepeatTarget: true,
    canTargetAllies: false,
    constraints: ['إذا حقق المحقق مع هدفك تظهر له نتيجة خاطئة.', 'لا تؤثر على الوزير أو الرسول.'],
    constraintsEn: ['If Seer investigates target, false result returned.', 'Does not affect Minister or Messenger.'],
  },
  {
    id: 'impersonator',
    name: 'المنتحل',
    nameEn: 'Impersonator',
    icon: '🎭',
    cardImage: '/cards/deset_impersonator.png',
    faction: Faction.shadow,
    roleType: RoleType.special,
    difficulty: Difficulty.hard,
    description: 'ينسخ قدرة ليلية من لاعب حي ليلة واحدة ويستخدمها.',
    descriptionEn: 'Copies a night ability from a living player for one night and uses it.',
    lore: 'أنا أي شخص تحتاجني أن أكون.',
    loreEn: 'I am anyone you need me to be.',
    goal: 'استخدام قوة الفرق الأخرى ضدها في ليلة واحدة فقط.',
    goalEn: 'Use rival powers against them for one night.',
    abilityDescription: 'اختر لاعباً حياً لنسخ قدرته الليلية، ثم اختر هدفاً تطلق القدرة عليه.',
    abilityDescriptionEn: 'Choose a living player to copy night ability, then choose a target.',
    priority: 30,
    nightAbilityKind: NightAbilityKind.copy,
    targetCount: 2,
    canTargetAllies: true,
    constraints: ['تنسخ القدرة لا الدور ولا المعرفة.', 'لا يمكنك نسخ الملك أو المواطن.'],
    constraintsEn: ['Copy ability only, not role or intel.', 'Cannot copy King or Citizen.'],
  },
  {
    id: 'slasher',
    name: 'السفاح',
    nameEn: 'Slasher',
    icon: '🩸',
    cardImage: '/cards/deset_slasher.png',
    faction: Faction.shadow,
    roleType: RoleType.attack,
    difficulty: Difficulty.medium,
    description: 'إذا نجح أول اغتيال، يحصل على هجوم إضافي مرة واحدة.',
    descriptionEn: 'If first assassination succeeds, gains one extra attack.',
    lore: 'عطش للدماء لا يمكن إطفاؤه.',
    loreEn: 'Thirst for blood that cannot be quenched.',
    goal: 'التصفية السريعة لأعضاء فريق المملكة.',
    goalEn: 'Rapid elimination of Kingdom members.',
    abilityDescription: 'بعد نجاح أول اغتيال لك، تحصل على استخدام إضافي لقدرة الهجوم مرة واحدة.',
    abilityDescriptionEn: 'After first successful kill, gain one extra attack ability use.',
    priority: 20,
    nightAbilityKind: NightAbilityKind.attack,
    targetCount: 1,
    canTargetAllies: false,
    cooldownOnFailureOnly: true,
    cooldownScale: [
      { maxPlayers: 7, cooldownDays: 2 },
      { maxPlayers: 11, cooldownDays: 3 },
      { maxPlayers: 15, cooldownDays: 4 },
      { maxPlayers: 20, cooldownDays: 5 },
    ],
    constraints: ['يجب أن تكون أنت منفذ الاغتيال.', 'عند نجاح أول اغتيال تحصل على استخدام إضافي واحد.'],
    constraintsEn: ['Must be killer for count.', 'Upon first success, gain one extra use.'],
  },

  // --- الشخصيات المحايدة (NEUTRAL) ---
  {
    id: 'trickster',
    name: 'المخادع',
    nameEn: 'Trickster',
    icon: '🃏',
    cardImage: '/cards/deset_trickster.png',
    faction: Faction.neutral,
    roleType: RoleType.special,
    difficulty: Difficulty.hard,
    description: 'لا ينتمي لأحد، ويريد أن تصوّتوا على استبعاده.',
    descriptionEn: 'Belongs to no one and wants to be voted out.',
    lore: 'يضحك وحده في آخر القاعة، ويعرف أن أقصر طريق للفوز هو أن تكرهوه.',
    loreEn: "Laughing alone at the hall's end, knowing hatred is the shortest path to victory.",
    goal: 'أن يتم استبعادك بالتصويت.',
    goalEn: 'Be eliminated by vote.',
    abilityDescription: 'سلاحك الوحيد هو الكلام: أقنع الطاولة حتى يصوّتوا على استبعادك وتفوز وحدك.',
    abilityDescriptionEn: 'Convince the table you are dangerous so they vote you out to win alone.',
    tips: ['ادّعِ أي دور تشاء.'],
    tipsEn: ['Claim any role.'],
    warnings: ['إن قُتلت ليلاً خسرت فوراً.'],
    warningsEn: ['If killed at night, you lose immediately.'],
    priority: 5,
    nightAbilityKind: NightAbilityKind.none,
    winRequiresDeath: true,
    constraints: ['إذا استُبعدت بالتصويت تفوز فوراً وتنتهي المباراة.', 'إذا مِتَّ بقدرة لاعب خسرت مباشرة.'],
    constraintsEn: ['If voted out, win instantly.', 'If killed at night, lose immediately.'],
  },
];
